// Generated by CoffeeScript 1.4.0
(function() {

  window.App = Em.Application.create();

  App.Environment = document.location.origin;

  App.Version = "0.1";

  App.ApplicationController = Em.Controller.extend();

  App.HomeController = Em.Controller.extend();

  App.ApplicationView = Em.View.extend({
    templateName: 'application'
  });

  App.HomeView = Em.View.extend({
    templateName: 'home'
  });

  App.Router = Em.Router.extend({
    location: 'history',
    root: Em.Route.extend({
      showHome: Em.Route.transitionTo('home'),
      home: Em.Route.extend({
        route: '/',
        connectOutlets: function(router) {
          return router.get('applicationController').connectOutlet('home');
        }
      })
    })
  });

  App.initialize();

}).call(this);
